	-------------FAST API - PRODUCTS LEARNING SCRIPT ---------------------------

create table products(
	product_id int generated by default as identity primary key,
	product_name varchar(255) not null,
	price int not null

);

alter table fastapi_db.public.products add column is_sale bool default false;
alter table fastapi_db.public.products add column inventory int not null default 0;
alter table fastapi_db.public.products add column created_at timestamp with time zone not null default now();

insert into fastapi_db.public.products (product_name, price) values ('TV', 200),
																	('DVD Players', 80),
																	('Remote', 10),
																	('Microphone',30),
																	('Car', 40);

insert into fastapi_db.public.products (product_name, price) values ('Pencil', 2);
insert into fastapi_db.public.products (product_name, price, is_sale) values ('Pencil Sharpener', 4, true);
insert into fastapi_db.public.products (product_name, price) values ('Keyboard', 28);
insert into fastapi_db.public.products (product_name, price, is_sale, inventory) values ('Soda', 2, true, 10),
																			 ('Pizza',13, true, 22),
																			 ('Toothbrush',2, true, 8),
																			 ('Toilet Paper', 4, false, 100),
																			 ('Xbox', 380, true, 45);

insert into fastapi_db.public.products (product_name, price) values
 ('TV RED',100),
 ('TV BLUE',200),
 ('TV YELLOW', 50);

insert into fastapi_db.public.products (product_name, price, inventory) values
 ('chicken',40, 10),
 ('chicken',40, 10),
 ('Tortilla', 4, 1000);

-- USING THE RETURNING KEYWORD TO SEND THE NELY INSERTED RECORDS BACK TO THE FRONTEND OR THE USER.
insert into fastapi_db.public.products (product_name, price, inventory) values ('car', 10000, 100) returning *;

insert into fastapi_db.public.products (product_name, price, inventory) 
values ('car', 10000, 100),('laptop',50, 25), ('monitor', 60, 4) 
returning *;

-- USING RETURNING WITH DELETE KEYWORD TO SEE WHAT THE DELETING RECORD LOOKED LIKE:
DELETE FROM products WHERE product_id in (10,11) RETURNING *;

--UPDATING RECORDS WITH RETURNING KEYWORD:
UPDATE products SET product_name='flour tortilla', price=40 WHERE product_id = 19 RETURNING *;
update products set is_sale = true where product_id = 5 returning *;
update products set is_sale = true where product_id > 15 returning *;

																							
delete from fastapi_db.public.products ;
truncate fastapi_db.public.products ;
drop table fastapi_db.public.products ;



---------------------------------------------------------------------------------------------------------------------------------------

select * from fastapi_db.public.products where inventory > 0 and price > 20;

-- DURING PAGENATION, WE WILL REQUIRE LIMIT AND OFFSET KEYWORDS IN OUR APIs.
select * from products order by product_id limit 5 offset 2;


